[package]
name = "libnotcurses-sys"
version = "3.0.0"
authors = [
	"nick black <dankamongmen@gmail.com>",
	"José Luis Cruz <joseluis@andamira.net>"
]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.56"
description = "Low-level Rust bindings for the notcurses C library."
documentation = "https://dankamongmen.github.io/notcurses/rustdoc/libnotcurses_sys/"
repository = "https://github.com/dankamongmen/notcurses"
homepage = "https://nick-black.com/dankwiki/index.php/Notcurses"
readme = "./README.md"
links = "notcurses"
build = "build/build.rs"
categories = [
	"external-ffi-bindings",
	"command-line-interface",
	"visualization",
	"multimedia",
	"rendering",
]
keywords = ["tui", "cli", "terminal", "ncurses", "ffi"]
include = [
	"/examples/hello-world-*.rs",
	"/examples/erase_region.rs",
	"/examples/info.rs",
	"/examples/input.rs",
	"/examples/pixel-cell.rs",
	"/examples/planes.rs",
	"/examples/utils/mod.rs",
	"/examples/utils/canvas.rs",
	"/examples/utils/counter.rs",
	"/build/build.rs",
	"/build/wrapper.h",
	"/src/",
	"/LICENSE-*",
	"/README.md"
]

[dependencies]
libc = { version = "^0.2.80", default-features = false }
cty = "^0.2.1"

[dev-dependencies]
rand = "^0.8"
serial_test = "^0.5.0"
serial_test_derive = "^0.5.0"

[build-dependencies]
bindgen = "^0.57"
pkg-config = "^0.3.18"

cc = { version = "^1.0", optional = true }
reqwest = { version = "0.11.5", features = ["blocking"], optional = true }
zip = { version = "0.5.13", optional = true }

[features]
compile_nc = ["cc", "reqwest", "zip"]

[package.metadata.docs.rs]
features = ["compile_nc"]

# https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
#
[profile.release]
# opt-level = 0            # [0-*3 | s | z]
# lto = "fat"              # [*fat | thin]
# debug = 1                # [*0/false | 1 | 2/true]
# debug-assertions = true  # [*false | true]
