[alias]
d = "doc --no-deps"
do = "doc --no-deps --open"

c = "clippy"

re = "run --example"

# TEST
# fix IO errors: https://github.com/dankamongmen/notcurses/issues/766
t = "test -- --test-threads 1 --nocapture"
