[alias]
d = "doc --no-deps"
do = "doc --no-deps --open"

re = "run --example"
rre = "run --release --example"

rqe = "run --quiet --example "
req = "rqe"

# TEST
# fix IO errors: https://github.com/dankamongmen/notcurses/issues/766
t = "test -- --test-threads 1 --nocapture"
t_all = "test --no-fail-fast -- --test-threads 1 --nocapture"
